### PR TITLE
Logic

### PR DESCRIPTION
**Pull request by enaburekhan**

### CODE REVIEW

**Comment by enaburekhan** [comment]
**Milestone 3: Game_Logic**
**In this project:**

- Create Logic, Position and ArrayOperation class
- Create the method logic on the various class
- Require it on the main file

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
## Changes Required #
**Hey @enaburekhan & @TSHEPO-CLOUD**  
Nice job so far, but there are some issues:
## Required changes #
- the game must have at least two classes (game, board) each of them containing their logic, and the main file run the game only, you can also make a Players class to store all the players' info.
- please remove the (Position, ArrayOperation) classes and replace them with methods inside the game, board classes
- the game doesn't check for winning cases it only checks for tie cases.

if you need any further clarifications you can contact me on slack @Mahmoud Mohammad

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
## Changes Requested # 
**hi @enaburekhan & @TSHEPO-CLOUD**
good job so far, there are still some issues with the project:
## Requested Changes # 
1- move each class into it's own file
2- move the method game_board into the game.rb file after creating it.
remember to move any logic to it's corresponding file.

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Status: Approved :heavy_check_mark:

### Hello Team! 

### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: :tada:

### You may merge, good luck with your next projects! :rocket:
### Happy Coding! :+1:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Pull request merged**
